global:
  scrape_interval: 5s
scrape_configs:
- job_name: aula
  static_configs:
    - targets:
      - 192.168.200.102:3030
- job_name: servidor
  static_configs:
    - targets:
      - localhost:9100